import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

interface PdfExpense {
  vendor: string;
  date: string;
  amount: number;
  category: string;
}

interface PdfData {
  employeeName: string;
  designation: string;
  expenses: PdfExpense[];
  totalAmount: number;
  submissionDate: string;
  reimbursementId: string;
  currencySymbol?: string;
}

export async function generateReimbursementPdf(data: PdfData): Promise<Uint8Array> {
  const cs = data.currencySymbol || "Rs.";
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);

  const page = doc.addPage([595, 842]); // A4
  const { height } = page.getSize();
  let y = height - 60;

  const darkBlue = rgb(0.1, 0.15, 0.35);
  const gray = rgb(0.4, 0.4, 0.4);
  const black = rgb(0, 0, 0);
  const lineColor = rgb(0.8, 0.8, 0.8);

  // Title
  page.drawText("REIMBURSEMENT CLAIM", {
    x: 50,
    y,
    size: 22,
    font: boldFont,
    color: darkBlue,
  });
  y -= 35;

  // Line
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 1, color: lineColor });
  y -= 25;

  // Employee details
  const drawField = (label: string, value: string) => {
    page.drawText(label, { x: 50, y, size: 10, font: boldFont, color: gray });
    page.drawText(value, { x: 180, y, size: 10, font, color: black });
    y -= 20;
  };

  drawField("Employee:", data.employeeName);
  drawField("Designation:", data.designation);
  drawField("Submission Date:", data.submissionDate);
  drawField("Reference ID:", data.reimbursementId);
  y -= 10;

  // Table header
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 1, color: lineColor });
  y -= 20;

  const cols = [50, 200, 310, 410, 490];
  const headers = ["Vendor", "Date", "Category", "Amount"];

  headers.forEach((h, i) => {
    page.drawText(h, { x: cols[i], y, size: 10, font: boldFont, color: darkBlue });
  });
  y -= 15;
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 0.5, color: lineColor });
  y -= 15;

  // Expense rows
  for (const expense of data.expenses) {
    if (y < 80) {
      // TODO: add new page for very long lists
      break;
    }
    page.drawText(expense.vendor.substring(0, 25), { x: cols[0], y, size: 9, font, color: black });
    page.drawText(expense.date, { x: cols[1], y, size: 9, font, color: black });
    page.drawText(expense.category, { x: cols[2], y, size: 9, font, color: black });
    page.drawText(`${cs}${expense.amount.toFixed(2)}`, { x: cols[3], y, size: 9, font, color: black });
    y -= 18;
  }

  y -= 5;
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 1, color: lineColor });
  y -= 20;

  // Total
  page.drawText("TOTAL:", { x: cols[2], y, size: 12, font: boldFont, color: darkBlue });
  page.drawText(`${cs}${data.totalAmount.toFixed(2)}`, {
    x: cols[3],
    y,
    size: 12,
    font: boldFont,
    color: darkBlue,
  });

  // Footer
  page.drawText("Generated by Reimbursement App", {
    x: 50,
    y: 30,
    size: 8,
    font,
    color: gray,
  });

  return doc.save();
}
